package band.mlgb.ghmasta2.model

import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Saves the next and previous page name of a repo
 */
@Entity(
    tableName = "user_repo_page_entity"
)
class UserRepoPageEntity(
    @Embedded
    val repo: Repo,
    val nextPage: Int
) {

    @PrimaryKey(autoGenerate = true)
    var autoGeneratedId: Int = 0
}